# Generated by Django 3.2.9 on 2021-12-11 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscleType', models.CharField(max_length=64)),
                ('exerciseType', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('hardness', models.TextField()),
                ('tags', models.JSONField(default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardness', models.CharField(max_length=64)),
                ('breaktime', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExercisePerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscleType', models.CharField(max_length=64)),
                ('exerciseType', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('hardness', models.TextField()),
                ('tags', models.JSONField(default=dict, null=True)),
                ('isFavorite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
