# Generated by Django 3.2.7 on 2021-11-07 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fitvox', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercisedefault',
            old_name='tag',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='exerciseperuser',
            old_name='tag',
            new_name='tags',
        ),
    ]
