# Generated by Django 3.2.10 on 2021-12-10 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Fitvox', '0002_auto_20211107_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(default=0)),
                ('bodyWeight', models.FloatField(default=-1.0)),
                ('skeletalMuscle', models.FloatField(default=-1.0)),
                ('bodyFat', models.FloatField(default=-1.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_partner', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='exerciseperuser',
            name='oneRMs',
        ),
        migrations.RemoveField(
            model_name='exerciseperuser',
            name='volumes',
        ),
        migrations.AlterField(
            model_name='exercisedefault',
            name='tags',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseperuser',
            name='isFavorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exerciseperuser',
            name='tags',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.0)),
                ('repetition', models.IntegerField(default=0)),
                ('breaktime', models.IntegerField(default=0)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='Fitvox.workoutentry')),
            ],
        ),
        migrations.AddField(
            model_name='workoutentry',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fitvox.exerciseperuser'),
        ),
        migrations.AddField(
            model_name='workoutentry',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='Fitvox.workoutdetail'),
        ),
        migrations.CreateModel(
            name='VolumeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(default=0)),
                ('volume', models.FloatField(default=0.0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume', to='Fitvox.exerciseperuser')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume', to='Fitvox.workoutset')),
            ],
        ),
        migrations.CreateModel(
            name='OneRMInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(default=0)),
                ('oneRM', models.FloatField(default=0.0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oneRM', to='Fitvox.exerciseperuser')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oneRM', to='Fitvox.workoutset')),
            ],
        ),
    ]
