export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const CREATEACCOUNT = 'CREATEACCOUNT'
export const FAILCREATEACCOUNT = 'FAILCREATEACCOUNT'

export const GET_SETTING = 'GET_SETTING'
export const CHANGE_SETTING = 'CHANGE_SETTING'

export const GET_EXERCISE_LIST = 'GET_EXERCISE_LIST'
export const ADD_EXERCISE = 'ADD_EXERCISE'

export const GET_WORKOUT_ENTRIES = 'GET_WORKOUT_ENTRIES'

export const GET_BODY_INFO = 'GET_BODY_INFO'
export const GET_STATISTICS = 'GET_STATISTICS'

export const START_VOICE_PARTNER = 'START_VOICE_PARTNER'
export const GET_WAV = 'GET_WAV'

export const GET_WORKOUT_SUMMARY = 'GET_WORKOUT_SUMMARY'

